### ISSUE TITLE
Error returned when using dialogService.OpenFolder or OpenFile .

### ISSUE THREAD

**Issue by pelva** [jamsoft/JamSoft.AvaloniaUI.Dialogs#2]
JamSoft.AvaloniaUI.Dialogs is an excellent component. But when I use OpenFolder or OpenFile, it returns a result normally when selecting folders in the dialog. However, the issue arises when I start selecting folders with spaces in their names. the spaces in the folder names have been replaced with "%20". This is very inconvenient for subsequent use, such as determining whether a file exists.
The reason for this problem is that AbsolutePath is used after calling storageProvider.OpenFolderPickerAsync.
![image](https://github.com/jamsoft/JamSoft.AvaloniaUI.Dialogs/assets/135562884/2ed33a28-ec26-4541-9b32-8c3decea19a2)

In addition, if you call OpenFolder, select nothing, and press Cancel, an error will be reported.

OS: [Windows 11]
Version [22H2]

**Comment by jamsoft** [comment]
I've identified the issue and implemented a fix ... going to do some more testing but should have a new release tomorrow.
