### ISSUE TITLE
MessageBox supports more icon types

### ISSUE THREAD

**Issue by pelva** [jamsoft/JamSoft.AvaloniaUI.Dialogs#3]
In MsBox.Avalonia, they support the following types
```
public enum Icon
{
    None,
    Battery,
    Database,
    Error,
    Folder,
    Forbidden,
    Info,
    Plus,
    Question,
    Setting,
    SpeakerLess,
    SpeakerMore,
    Stop,
    Stopwatch,
    Success,
    Warning,
    Wifi
}
```
In my opinion, the success type is very useful for displaying a successful dialog box.

So can we support more icon types?

In addition, since messageBoxService.Show is an asynchronous method, wouldn’t it be better to add Async?

**Comment by jamsoft** [comment]
I've just released a new version of the package (1.3.1) with additional icons.

**Comment by pelva** [comment]
Thank you for making the updates based on my suggestions.  Great job!

**Comment by jamsoft** [comment]
No problem. It was a good suggestion so, LETS GO! :)
